costmap:
  radius: 1.2
  obstacle_maps: 
    - revit_c_shape_1
    - revit_c_shape_2
    - revit_c_shape_3
    - revit_c_shape_4
    - revit_c_shape_5
    - revit_c_shape_6
    - revit_c_shape_7
    - revit_c_shape_8
    - revit_c_shape_9
    - revit_c_shape_10
