training:
  timesteps: 10000
  algorithm: SAC
  batch_size: 1024
  buffer_size: 1000000
  model_name: SAC
  
  continue_training: False
  model_path: /data/rl_data/training_env_no_object_2/models/SAC_190000.zip